//------------------------------------------------------------------------------
// <auto-generated>
//     Mã này được tạo ra bởi một công cụ.
//     Phiên bản Runtime: 4.0.30319.42000
//
//     Những thay đổi trong file này có thể gây ra hành vi không chính xác và sẽ bị mất nếu
//     mã được tạo lại.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASTEROIDS
{
    using System;

    /// <summary>
    ///   Một lớp tài nguyên kiểu mạnh, dùng để tra cứu các chuỗi local hóa, v.v.
    /// </summary>
    // Lớp này được tự động tạo ra bởi lớp StronglyTypedResourceBuilder
    // thông qua một công cụ như ResGen hoặc Visual Studio.
    // Để thêm hoặc xóa một thành viên, hãy chỉnh sửa file .ResX của bạn và sau đó chạy lại ResGen
    // với tùy chọn /str, hoặc xây dựng lại dự án VS của bạn.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUser CodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AsteroidsResources
    {

        private static global::System.Resources.ResourceManager resourceMan; // Trình quản lý tài nguyên
        private static global::System.Globalization.CultureInfo resourceCulture; // Thông tin văn hóa của tài nguyên

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AsteroidsResources()
        { // Hàm khởi tạo cho lớp AsteroidsResources
        }

        /// <summary>
        ///   Trả về thể hiện ResourceManager đã được lưu vào bộ nhớ cache được sử dụng bởi lớp này.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                // Kiểm tra xem resourceMan có null hay không
                if (object.ReferenceEquals(resourceMan, null))
                {
                    // Nếu null, khởi tạo một ResourceManager mới
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASTEROIDS.AsteroidsResources", typeof(AsteroidsResources).Assembly);
                    resourceMan = temp; // Gán ResourceManager mới cho resourceMan
                }
                return resourceMan; // Trả về ResourceManager
            }
        }

        /// <summary>
        ///   Ghi đè thuộc tính CurrentUICulture của luồng hiện tại cho tất cả
        ///   các tra cứu tài nguyên sử dụng lớp tài nguyên kiểu mạnh này.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture; // Trả về thông tin văn hóa
            }
            set
            {
                resourceCulture = value; // Gán thông tin văn hóa mới
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên local hóa có kiểu System.IO.UnmanagedMemoryStream tương tự như System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream DestroyedAsteroidLarge
        {
            get
            {
                return ResourceManager.GetStream("DestroyedAsteroidLarge", resourceCulture); // Trả về luồng tài nguyên cho tiểu hành tinh lớn bị phá hủy
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên local hóa có kiểu System.IO.UnmanagedMemoryStream tương tự như System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream DestroyedAsteroidMedium
        {
            get
            {
                return ResourceManager.GetStream("DestroyedAsteroidMedium", resourceCulture); // Trả về luồng tài nguyên cho tiểu hành tinh vừa bị phá hủy
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên local hóa có kiểu System.IO.UnmanagedMemoryStream tương tự như System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream DestroyedAsteroidSmall
        {
            get
            {
                return ResourceManager.GetStream("DestroyedAsteroidSmall", resourceCulture); // Trả về luồng tài nguyên cho tiểu hành tinh nhỏ bị phá hủy
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên local hóa có kiểu System.IO.UnmanagedMemoryStream tương tự như System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Projectile
        {
            get
            {
                return ResourceManager.GetStream("Projectile", resourceCulture); // Trả về luồng tài nguyên cho vật thể bay
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên local hóa có kiểu System.IO.UnmanagedMemoryStream tương tự như System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SpaceShipLarge
        {
            get
            {
                return ResourceManager.GetStream("SpaceShipLarge", resourceCulture); // Trả về luồng tài nguyên cho tàu vũ trụ lớn
            }
        }

        /// <summary>
        ///   Tra cứu một tài nguyên local hóa có kiểu System.IO.UnmanagedMemoryStream tương tự như System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SpaceShipSmall
        {
            get
            {
                return ResourceManager.GetStream("SpaceShipSmall", resourceCulture); // Trả về luồng tài nguyên cho tàu vũ trụ nhỏ
            }
        }
    }
}